// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3h-OutEla4kU3SFwi1KTM79XVXrC1R5M',
    appId: '1:20517091319:web:8dc5006a6240766556a0f2',
    messagingSenderId: '20517091319',
    projectId: 'linkmind-917b4',
    authDomain: 'linkmind-917b4.firebaseapp.com',
    storageBucket: 'linkmind-917b4.firebasestorage.app',
    measurementId: 'G-J3GRBNG40B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU1Zq0Y-uweOYmACbPNMr18FMVJLSFexM',
    appId: '1:20517091319:android:73f7d0fd55cd4ba056a0f2',
    messagingSenderId: '20517091319',
    projectId: 'linkmind-917b4',
    storageBucket: 'linkmind-917b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPK-iwFxgNg-2Gct-n1RgGNnRvuvQIuQc',
    appId: '1:20517091319:ios:2b32fcec531a74ff56a0f2',
    messagingSenderId: '20517091319',
    projectId: 'linkmind-917b4',
    storageBucket: 'linkmind-917b4.firebasestorage.app',
    iosBundleId: 'com.LinkMind.LinkMind',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPK-iwFxgNg-2Gct-n1RgGNnRvuvQIuQc',
    appId: '1:20517091319:ios:2b32fcec531a74ff56a0f2',
    messagingSenderId: '20517091319',
    projectId: 'linkmind-917b4',
    storageBucket: 'linkmind-917b4.firebasestorage.app',
    iosBundleId: 'com.LinkMind.LinkMind',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3h-OutEla4kU3SFwi1KTM79XVXrC1R5M',
    appId: '1:20517091319:web:f960f3ba3559749f56a0f2',
    messagingSenderId: '20517091319',
    projectId: 'linkmind-917b4',
    authDomain: 'linkmind-917b4.firebaseapp.com',
    storageBucket: 'linkmind-917b4.firebasestorage.app',
    measurementId: 'G-Q4R6LWGZGH',
  );
}
